matrix:
  include:
    - language: node_js
      node_js: 8
      before_script:
        - cd src/main/ui
        - npm install -g npm@latest
        - npm install
      script:
        - npm run build:dev

    - language: java
      jdk: openjdk8
      script:
        - mvn clean install
